title: The Solution Architect Survival Guide
description: >-
  Practical career lessons on solution architecture, system design and enterprise architecture: principles, methodologies, frameworks, and real world examples of news worthy failures, and what could have been done to mitigate those failures.
theme: minima
minima:
  skin: dark

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - about.md

show_excerpts: true

permalink: /:year/:month/:day/:title/

# Site owner / social (edit as you like)
author:
  name: Michael Rossi

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
